id: I04D8DCD2
legacy_id: P009127
ocr_import_info:
  bdrc_scan_id: W00EGS1016983
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T08:04:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:53:48.439098+00:00'
last_modified: 2022-08-29 18:54:18.583213
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016983
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016983
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན་གྱི་རྣམ་ཐར།
  author: སྐྱེ་རྒུ་མཁན་པོ་འཕྲིན་ལས་ཆོས་འཕེལ།
statistics:
  ocr_word_mean_confidence_index: 0.9218480213582053
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I00EGS1016992:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1016992
      total_pages: 280
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1016992.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9218480213582053
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
